### PR TITLE
Match VideoSys__Reset

### PR DESCRIPTION
**Pull request by AnOpenSauceDev**
https://decomp.me/scratch/BtUd1

### CODE REVIEW

**Comment by xPythh** [comment]
Pretty good, can you please rename the functions that are used ?
I can see that func_800309E4  is an Library method https://i.imgur.com/0Niv1g2.png
I can see that func_8002CFBC is an Library Method https://i.imgur.com/dOGtPvH.png
Cheers

**Comment by xPythh** [comment]
Hey @AnOpenSauceDev can you let me know how is that PR going ? If you cannot finish it let me know I will try to work on it.

**Comment by AnOpenSauceDev** [comment]
> Hey @AnOpenSauceDev can you let me know how is that PR going ? If you cannot finish it let me know I will try to work on it.

I went to sleep after this (Australia Timezone), I'll work on this some more.

**Comment by AnOpenSauceDev** [comment]
Just renamed the methods to those two over there.

**Comment by xPythh** [comment]
I recieved your pull request, you were on an old version of the repository so I had to edit manually your pull request.
You made several mistakes:
1. The functions that you use (SetDispMask, VSync [or any others on future functions] need to have their symbols defined.
   When im pushing the changes, you will se in ./config/symbols.sces028.txt that i added the symbols
   They are directly the memory address of the original .EXE functions

2. You forgot to add in the globals.h the functions (in order to suppress implicit warnings that comes from it)
    It isn't vital but hey, better doing that !

**Comment by xPythh** [comment]
I have pushed on the main branch your code.
For the next times, make sure to be up to date on the main branch (we work on it alot, so it changes almost everyday !)
Thanks for your time, also added you in the credits 😄

**Comment by AnOpenSauceDev** [comment]
no problem!

**Pull request closed without merging**
